logging:
  file:
    name: /home/kidusmt/Documents/CS590-SA/elk-linux/spring-boot-elk2.log

server:
  port: 8091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
  application:
    name: CustomerService
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
  server:
    enableSelfPreservation: false
app:
  topic:
    customertopic: customer